In [1]:
import numpy as np

In [2]:
a = np.array([11, 23], dtype='float64')

In [3]:
a

array([11., 23.])

In [4]:
print(a)

[11. 23.]


In [6]:
a.shape

(2,)

In [7]:
print(np.sqrt(a))

[3.31662479 4.79583152]


In [8]:
print(a)

[11. 23.]


In [9]:
print(np.multiply(2,a))

[22. 46.]


In [10]:
a = np.random.randn(2,4)

In [11]:
a

array([[ 0.31995838,  0.65702877, -1.78731035, -1.32030738],
       [-0.55805339, -0.86282225,  1.6121049 ,  0.09514435]])

In [12]:
a * 1

array([[ 0.31995838,  0.65702877, -1.78731035, -1.32030738],
       [-0.55805339, -0.86282225,  1.6121049 ,  0.09514435]])

In [13]:
a * 10

array([[  3.19958384,   6.57028775, -17.87310353, -13.20307376],
       [ -5.58053389,  -8.6282225 ,  16.12104901,   0.95144351]])

In [14]:
a

array([[ 0.31995838,  0.65702877, -1.78731035, -1.32030738],
       [-0.55805339, -0.86282225,  1.6121049 ,  0.09514435]])

In [15]:
a = np.array(a*10)

In [16]:
a

array([[  3.19958384,   6.57028775, -17.87310353, -13.20307376],
       [ -5.58053389,  -8.6282225 ,  16.12104901,   0.95144351]])

In [17]:
print(a.mean())

-2.305321197790639


In [20]:
print(a.mean(axis=1))

[-5.32657643  0.71593403]


In [22]:
print(np.median(a, axis=0))

[-1.19047503 -1.02896738 -0.87602726 -6.12581513]
